# fly.toml app configuration file generated for bothire-autogen
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bothire-autogen"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8081"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512 