#!/bin/bash

echo "🔍 GitHub OAuth App Configuration Check"
echo "========================================"
echo ""
echo "Your current OAuth App Client ID: Ov23li6hQFeDxfWd5qcp"
echo ""
echo "1. Go to: https://github.com/settings/developers"
echo "2. Click on your OAuth App"
echo "3. Check the 'Authorization callback URL' field"
echo ""
echo "❌ If it shows: http://localhost:8081/api/auth/callback"
echo "   This is why it's redirecting to localhost!"
echo ""
echo "✅ It should be: https://bothire-autogen.fly.dev/api/auth/callback"
echo ""
echo "🔧 SOLUTION:"
echo "   Either update the existing app's callback URL"
echo "   OR create a separate OAuth app for production"
echo ""
echo "📝 Recommended: Create TWO OAuth apps:"
echo "   - Dev App: localhost callback"
echo "   - Prod App: fly.dev callback" 