#!/bin/bash

echo "🔐 OAuth Setup Guide for AutoGen Studio"
echo "========================================"
echo ""
echo "This guide will help you set up GitHub OAuth for both local and production environments."
echo ""

echo "📋 CURRENT STATUS:"
echo "- ✅ Environment-based auth.yaml created"
echo "- ✅ Local .env file created with production credentials (temporary)"
echo "- ✅ Production environment variables ready"
echo "- ✅ Scripts updated to load environment variables"
echo ""

echo "🔧 IMMEDIATE SOLUTION (to fix the localhost redirect issue):"
echo ""
echo "1. 📱 Update your GitHub OAuth App callback URL:"
echo "   - Go to: https://github.com/settings/developers"
echo "   - Click your OAuth App (Client ID: Ov23li6hQFeDxfWd5qcp)"
echo "   - Change 'Authorization callback URL' to:"
echo "     https://bothire-autogen.fly.dev/api/auth/callback"
echo "   - This will fix the production site immediately!"
echo ""

echo "2. 🚀 Set up production secrets and deploy:"
echo "   ./scripts/setup-fly-secrets.sh"
echo "   fly deploy --app bothire-autogen"
echo ""

echo "📚 RECOMMENDED LONG-TERM SETUP:"
echo ""
echo "Create separate GitHub OAuth Apps for better security:"
echo ""
echo "🏠 LOCAL DEVELOPMENT APP:"
echo "   - Name: 'AutoGen Studio (Local)'"
echo "   - Homepage URL: http://localhost:8081"
echo "   - Callback URL: http://localhost:8081/api/auth/callback"
echo "   - Update .env with these new credentials"
echo ""
echo "🌐 PRODUCTION APP (current):"
echo "   - Name: 'AutoGen Studio'"
echo "   - Homepage URL: https://bothire-autogen.fly.dev"
echo "   - Callback URL: https://bothire-autogen.fly.dev/api/auth/callback"
echo "   - Keep current production credentials"
echo ""

echo "📁 FILE STRUCTURE:"
echo "   auth.yaml              # Template with environment variables"
echo "   .env                  # Local development environment"
echo "   Dockerfile            # Production environment variables"
echo "   scripts/studio.sh     # Loads .env and starts AutoGen Studio"
echo ""

echo "🎯 QUICK START:"
echo "1. Update GitHub OAuth app callback URL (see step 1 above)"
echo "2. Run: ./scripts/setup-fly-secrets.sh"
echo "3. Run: fly deploy --app bothire-autogen"
echo "4. Production OAuth should work!"
echo ""
echo "5. For local testing:"
echo "   - Update your .env file with your OpenAI API key"
echo "   - Run: ./scripts/studio.sh"
echo ""

echo "💡 The system now automatically uses the right configuration:"
echo "   - Local: Uses .env file values"
echo "   - Production: Uses Fly.io environment variables"
echo ""
echo "🔗 Links:"
echo "   - GitHub OAuth Apps: https://github.com/settings/developers"
echo "   - Production Site: https://bothire-autogen.fly.dev"
echo "   - Fly.io Dashboard: https://fly.io/apps/bothire-autogen" 